### PR TITLE
added default image, + tests

### PR DESCRIPTION
**Pull request by ANovitsky**
added type of default image, + tests

### CODE REVIEW

**Comment by ANovitsky** [comment]
Can you merge this pull request, and update nuget pack?

**Comment by aloisdg** [comment]
I will try your code next week. I am moving form France to India tomorrow. I think it can wait a week :)

Looks great !

**Comment by aloisdg** [comment]
Everything is working so far. Thank you!

**Comment by aloisdg** [comment]
[NuGet package is updated](https://www.nuget.org/packages/Gravimage/).

**Pull request merged**
